[project]
title = "Health Data | Preswald"
version = "0.1.0"
port = 8501

[branding]
name = "Health Data"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#f06271"

[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
